import { useEffect, useState } from "react";
import type { Route } from "./+types/home";
import { getErrorMessage, trpc } from "../../lib/trpc";

export function meta({}: Route.MetaArgs) {
	return [{ title: "Basic React NodeMailer" }, { name: "description", content: "Generated by create-react-app" }];
}

export default function Home() {
	const [value, setValue] = useState<string>("");
	const [success, setSuccess] = useState<string | null>(null);
	const [error, setError] = useState<string | null>(null);
	const [isLoading, setIsLoading] = useState<boolean>(false);

	const [seconds, setSeconds] = useState<number>(0);
	const [isTimerActive, setIsTimerActive] = useState<boolean>(false);

	useEffect(() => {
		let interval = undefined;

		if (isTimerActive && seconds > 0) {
			interval = setInterval(() => {
				setSeconds((prev) => prev - 1);
			}, 1000);
		} else if (seconds === 0) {
			setIsTimerActive(false);
			clearInterval(interval);
			setSuccess(null);
		}
		return () => clearInterval(interval);
	}, [isTimerActive, seconds]);

	async function handleButtonClick(e: React.SubmitEvent<HTMLFormElement>) {
		e.preventDefault();

		setSuccess(null);
		setError(null);

		setIsLoading(true);
		try {
			await trpc.sendEmail.mutate({ email: value.trim() });
			setValue("");
			setSuccess("Email sent successfully!");
			setSeconds(10);
			setIsTimerActive(true);
		} catch (err) {
			setError(getErrorMessage(err, "Server connection error."));
		} finally {
			setIsLoading(false);
		}
	}
	return (
		<div className="flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black h-screen">
			<main className="flex flex-1 w-full max-w-3xl flex-col items-center justify-center py-32 px-16 bg-white dark:bg-black sm:items-start">
				<form
					onSubmit={handleButtonClick}
					className="flex flex-col items-center gap-6 text-center sm:items-start sm:text-left"
				>
					<div className="w-125">
						<h1 className="text-3xl font-semibold leading-10 tracking-tight text-black dark:text-zinc-50 mb-[0.5em]">
							Basic React NodeMailer (tRPC)
						</h1>
						<p className="text-black dark:text-zinc-50 mb-[2em]">React Router · Express.js</p>
						<label
							htmlFor="email"
							className="block mb-2.5 text-sm font-medium text-heading"
						>
							Email
						</label>
						<div className="relative">
							<input
								type="email"
								id="email"
								name="email"
								className="block w-full p-3 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 placeholder:text-body disabled:opacity-50 disabled:cursor-not-allowed transition-all"
								value={value}
								placeholder="john.doe@domain.com"
								autoComplete="email"
								required
								onChange={(e) => setValue(e.target.value)}
							/>
							<button
								type="submit"
								className="absolute inset-e-1.5 bottom-1.5 text-black bg-white hover:bg-brand-strong box-border border border-transparent focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 shadow-xs font-medium leading-5 rounded text-xs px-3 py-2 disabled:opacity-50 disabled:cursor-not-allowed transition-all hover:cursor-pointer hover:bg-white/90"
								disabled={isLoading || seconds > 0}
							>
								{isLoading ? "Sending..." : "Send"}
							</button>
						</div>
						{success && <p className="mt-2.5 font-medium text-sm text-green-400">{success}</p>}
						{error && <p className="mt-2.5 font-medium text-sm text-red-400">{error}</p>}
						{seconds > 0 && (
							<p className="font-medium text-sm text-blue-400">Please wait {seconds}s before sending another email.</p>
						)}
					</div>
				</form>
			</main>
		</div>
	);
}
